### ISSUE TITLE
AttributeError: 'int' object has no attribute 'value'

### ISSUE THREAD

**Issue by AqsaHassan** [sergiomsilva/alpr-unconstrained#101]
Using TensorFlow backend.
2019-11-18 14:10:11.658100: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-11-18 14:10:11.679120: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3192000000 Hz
2019-11-18 14:10:11.680140: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x563b23931330 executing computations on platform Host. Devices:
2019-11-18 14:10:11.680166: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version
Traceback (most recent call last):
  File "train-detector.py", line 74, in <module>
    model,model_stride,xshape,yshape = load_network(args.model,dim)
  File "train-detector.py", line 31, in load_network
    output_shape = tuple([s.value for s in outputs.shape[1:]])
AttributeError: 'int' object has no attribute 'value'
 Could  please you tell why I'm getting this error and how to fix it?

**Comment by lagerkoller** [comment]
Hello @AqsaHassan,
I have the same problem. Did you come up with a solution? Here is the complete output: 

`(venv) johannes@Johanness-MacBook-Pro:~/../alpr-unconstrained$ python train-detector.py --model models/eccv-model-scracth --name my-trained-model --train-dir samples/train-detector --output-dir models/my-trained-model/ -op Adam -lr .001 -its 300000 -bs 64
Using TensorFlow backend.
2020-03-31 14:49:46.625361: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-03-31 14:49:46.635163: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7f8183430310 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-03-31 14:49:46.635178: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
Traceback (most recent call last):
  File "train-detector.py", line 74, in <module>
    model,model_stride,xshape,yshape = load_network(args.model,dim)
  File "train-detector.py", line 31, in load_network
    output_shape = tuple([s.value for s in outputs.shape[1:]])
AttributeError: 'int' object has no attribute 'value'
`

**Comment by lagerkoller** [comment]
mhm, I tried the same command in a new terminal window today and it worked. I don't know, maybe the example servers were down or something.

**Comment by AqsaHassan** [comment]
that's great... Thank you!

**Comment by lagerkoller** [comment]
I figured out what the problem was. Line 33 of train-detector should not be 
`output_shape = tuple([s.value for s in outputs.shape[1:]])`
but 
`output_shape = tuple([s for s in outputs.shape[1:]])`.

Also line 8 of loss.py should not be
`Pred = -tf.math.log(Pred)`
but 
`Pred = -tf.log(Pred)`
