### ISSUE TITLE
Create custom model for 230.000 images

### ISSUE THREAD

**Issue by ogulcankarayel5** [sergiomsilva/alpr-unconstrained#105]
I have jpg files that contains 230.000 car plate images for graduate project and i'm new for this topic.
What exactly should I do for plate recognation. Which format should I use and how can I convert 230.000 images to data format that you will say.

**Comment by Frank-qlu** [comment]
I also do the lp. can i disscuss with you?

**Comment by ogulcankarayel5** [comment]
Of course, please contact me

**Comment by laurentdebricon** [comment]
Share the knowledge here ! :D i'm listening also, watching forks ...

**Comment by ogulcankarayel5** [comment]
@Frank-qlu do you have annotations

**Comment by Frank-qlu** [comment]
> @Frank-qlu do you have annotations

i have some annotations,but my tranning have some problem

**Comment by ogulcankarayel5** [comment]
What kind of problem

**Comment by Frank-qlu** [comment]
> What kind of problem

python2 train-detector.py --model models/eccv-model-scracth --name my-trained-model --train-dir samples/train-detector --output-dir models/my-trained-model/ -op Adam -lr .001 -its 30 -bs 64
Using TensorFlow backend.
2019-11-26 11:32:38.850268: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2799995000 Hz
2019-11-26 11:32:38.854033: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x5c7ece0 executing computations on platform Host. Devices:
2019-11-26 11:32:38.854058: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version
Traceback (most recent call last):
  File "train-detector.py", line 74, in <module>
    model,model_stride,xshape,yshape = load_network(args.model,dim)
  File "train-detector.py", line 31, in load_network
    output_shape = tuple([s.value for s in outputs.shape[1:]])
AttributeError: 'int' object has no attribute 'value'

**Comment by Frank-qlu** [comment]
> Share the knowledge here ! :D i'm listening also, watching forks ...

Using TensorFlow backend.
2019-11-18 14:10:11.658100: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-11-18 14:10:11.679120: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3192000000 Hz
2019-11-18 14:10:11.680140: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x563b23931330 executing computations on platform Host. Devices:
2019-11-18 14:10:11.680166: I tensorflow/compiler/xla/service/service.cc:175] StreamExecutor device (0): Host, Default Version
Traceback (most recent call last):
File "train-detector.py", line 74, in 
model,model_stride,xshape,yshape = load_network(args.model,dim)
File "train-detector.py", line 31, in load_network
output_shape = tuple([s.value for s in outputs.shape[1:]])
AttributeError: 'int' object has no attribute 'value'
Could please you tell why I'm getting this error and how to fix it?

**Comment by aesoruk** [comment]
> > Share the knowledge here ! :D i'm listening also, watching forks ...
> 
> Using TensorFlow backend.
> 2019-11-18 14:10:11.658100: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
> 2019-11-18 14:10:11.679120: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 3192000000 Hz
> 2019-11-18 14:10:11.680140: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x563b23931330 executing computations on platform Host. Devices:
> 2019-11-18 14:10:11.680166: I tensorflow/compiler/xla/service/service.cc:175] StreamExecutor device (0): Host, Default Version
> Traceback (most recent call last):
> File "train-detector.py", line 74, in
> model,model_stride,xshape,yshape = load_network(args.model,dim)
> File "train-detector.py", line 31, in load_network
> output_shape = tuple([s.value for s in outputs.shape[1:]])
> AttributeError: 'int' object has no attribute 'value'
> Could please you tell why I'm getting this error and how to fix it?

did you solve this problem ?

**Comment by flackpoint** [comment]
Had the same problem with python 3.7  

I didn't yet fully test it, but at least the error above is gone and the Iterations are running now.

Made the following changes: 

---

**train-detector.py**

Line 31:
```py
	output_shape = tuple([s for s in outputs.shape[1:]])
```

Line 102:
```py
	Ytrain = np.empty((batch_size, int(dim/model_stride), int(dim/model_stride), 2*4+1))
```

---

**src/sampler.py**

Line 15:
```py
	outsize = int(dim/stride)
```

---

**src/loss.py**

Line 8:
```py
	Pred = -tf.math.log(Pred)
```

---
