### ISSUE TITLE
have some problems after running

### ISSUE THREAD

**Issue by zrl4836** [sergiomsilva/alpr-unconstrained#14]
hello,I have some problems after running, can you help me answer it?
Traceback (most recent call last):
  File "vehicle-detection.py", line 7, in <module>
    import darknet.python.darknet as dn
ImportError: No module named darknet.python.darknet
Using TensorFlow backend.
Searching for license plates using WPOD-NET
Traceback (most recent call last):
  File "license-plate-ocr.py", line 7, in <module>
    import darknet.python.darknet as dn
ImportError: No module named darknet.python.darknet
Traceback (most recent call last):
  File "gen-outputs.py", line 30, in <module>
    Lcar = lread(detected_cars_labels)
  File "/home/toor/alpr-unconstrained-master/alpr-unconstrained-master/src/label.py", line 54, in lread
    with open(file_path,'r') as fd:
IOError: [Errno 2] No such file or directory: '/tmp/output/03009_cars.txt'

**Comment by sergiomsilva** [comment]
It seems to me that you didn't compile the darknet framework. Take a look at the "Requirements" section in the readme file. Please let me know if that doesn't help.

**Comment by zrl4836** [comment]
Thanks!I have solved it.Because I lacks configuration about my ubuntu in win10.
