### ISSUE TITLE
what is the class tpye error?

### ISSUE THREAD

**Issue by soaka0721** [sergiomsilva/alpr-unconstrained#30]
Traceback (most recent call last):
  File "vehicle-detection.py", line 25, in <module>
    vehicle_net  = dn.load_net(vehicle_netcfg, vehicle_weights, 0)
ctypes.ArgumentError: argument 1: <class 'TypeError'>: wrong type
Using TensorFlow backend.
2018-12-06 16:27:07.584695: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX AVX2 FMA
Searching for license plates using WPOD-NET
Traceback (most recent call last):
  File "license-plate-ocr.py", line 23, in <module>
    ocr_net  = dn.load_net(ocr_netcfg, ocr_weights, 0)

**Comment by linzhi123** [comment]
Maybe you need to convert it to ascii code.decode('ascii') @soaka0721

**Comment by soaka0721** [comment]
> Maybe you need to convert it to ascii code.decode('ascii') @soaka0721

thank you for your answer

what is the convert it means? 
run.sh or build darknet

**Comment by linzhi123** [comment]
ocr_weights = './yolov2-voc_final.weights'.encode('ascii')'
    ocr_netcfg  = './yolov2-voc.cfg'.encode('ascii')'
    ocr_dataset = './voc.data'.encode('ascii')'
like this

**Comment by plguhur** [comment]
This error disappeared for me when I used Python 2 instead of Python 3

**Comment by kelvin-jose** [comment]
If you're using Python3 you should be using
               ```
                vehicle_weights = bytes('data/vehicle-detector/yolo-voc.weights', encoding="utf-8")
		vehicle_netcfg  = bytes('data/vehicle-detector/yolo-voc.cfg', encoding="utf-8")
		vehicle_dataset = bytes('data/vehicle-detector/voc.data', encoding="utf-8")
```

**Comment by azhaoaigaga** [comment]
File "/home/zhaolzlz/Desktop/alpr-unconstrained/darknet/python/darknet.py", line 127, in detect
im = load_image(image, 0, 0)
ctypes.ArgumentError: argument 1: <class 'TypeError'>: wrong type
Excuse me, why is there a type error here

**Comment by MichZipp** [comment]
> File "/home/zhaolzlz/Desktop/alpr-unconstrained/darknet/python/darknet.py", line 127, in detect
> im = load_image(image, 0, 0)
> ctypes.ArgumentError: argument 1: <class 'TypeError'>: wrong type
> Excuse me, why is there a type error here

@azhaoaigaga I got the same error. How did you solve it?
