### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by mad0511** [sergiomsilva/alpr-unconstrained#75]
Traceback (most recent call last):
  File "vehicle-detection.py", line 6, in <module>
    import darknet.python.darknet as dn
  File "D:\alpr-unconstrained-master\alpr-unconstrained-master\darknet\python\darknet.py", line 48, in <module>
    lib = CDLL("darknet/libdarknet.so", RTLD_GLOBAL)
  File "C:\Users\User\Anaconda3\envs\tens\lib\ctypes\__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found

**Comment by PhilipsKoshy** [comment]
You probably did not build darknet library. First, you need to do "cd darknet && make" to build it.

**Comment by Sahilsk99** [comment]
I am using Windows then How can I build Darknet libarary in windows I am getting same error

Traceback (most recent call last):
File "vehicle-detection.py", line 6, in
import darknet.python.darknet as dn
File "D:\alpr-unconstrained-master\alpr-unconstrained-master\darknet\python\darknet.py", line 48, in
lib = CDLL("darknet/libdarknet.so", RTLD_GLOBAL)
File "C:\Users\User\Anaconda3\envs\tens\lib\ctypes_init_.py", line 356, in init
self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] The specified module could not be found

**Comment by talalz94** [comment]
> I am using Windows then How can I build Darknet libarary in windows I am getting same error
> 
> Traceback (most recent call last):
> File "vehicle-detection.py", line 6, in
> import darknet.python.darknet as dn
> File "D:\alpr-unconstrained-master\alpr-unconstrained-master\darknet\python\darknet.py", line 48, in
> lib = CDLL("darknet/libdarknet.so", RTLD_GLOBAL)
> File "C:\Users\User\Anaconda3\envs\tens\lib\ctypes_init_.py", line 356, in init
> self._handle = _dlopen(self._name, mode)
> OSError: [WinError 126] The specified module could not be found

did you find the solution?
